/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as R404Import } from './routes/__404'

// Create Virtual Routes

const LayoutIndexLazyImport = createFileRoute('/_layout/')()
const LayoutRegisterLazyImport = createFileRoute('/_layout/register')()
const LayoutLoginLazyImport = createFileRoute('/_layout/login')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const R404Route = R404Import.update({
  id: '/__404',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout.index.lazy').then((d) => d.Route))

const LayoutRegisterLazyRoute = LayoutRegisterLazyImport.update({
  path: '/register',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout.register.lazy').then((d) => d.Route),
)

const LayoutLoginLazyRoute = LayoutLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout.login.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__404': {
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/login': {
      preLoaderRoute: typeof LayoutLoginLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/register': {
      preLoaderRoute: typeof LayoutRegisterLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexLazyImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  R404Route,
  LayoutRoute.addChildren([
    LayoutLoginLazyRoute,
    LayoutRegisterLazyRoute,
    LayoutIndexLazyRoute,
  ]),
])

/* prettier-ignore-end */
