/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EKtigfEiXUx
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function RegisterForm() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100">
      <div className="min-w-[450px] max-w-lg rounded-lg bg-white p-8 shadow-md">
        <h1 className="mb-6 text-center text-4xl font-bold">Sign Up</h1>
        <form>
          <div className="mb-4">
            <label
              className="block text-sm font-medium text-gray-700"
              htmlFor="username"
            >
              Username
            </label>
            <Input
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
              id="username"
              placeholder="Username"
              type="text"
            />
          </div>
          <div className="mb-4">
            <label
              className="block text-sm font-medium text-gray-700"
              htmlFor="email"
            >
              Email
            </label>
            <Input
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
              id="email"
              placeholder="Email"
              type="email"
            />
          </div>
          <div className="mb-6">
            <label
              className="block text-sm font-medium text-gray-700"
              htmlFor="password"
            >
              Password
            </label>
            <Input
              className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
              id="password"
              placeholder="Password"
              type="password"
            />
          </div>
          <div className="mb-4">
            <Button className="w-full bg-blue-600 text-white">Submit</Button>
          </div>
          <div className="text-center">
            <p className="text-sm">
              Already have an account?{" "}
              <a className="text-blue-600 hover:underline" href="/login">
                Login
              </a>
            </p>
          </div>
        </form>
      </div>
    </div>
  );
}
